- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  period: 10s
  hosts: ["unix:///var/run/docker.sock"]
  enabled: false