#==========================  Modules configuration ============================
metricbeat.config.modules:
  path: ${LOGZIO_MODULES_PATH}/*.yml

#================================ General =====================================
fields:
  logzio_codec: json
  type: docker-collector-metrics
fields_under_root: true
#================================ Outputs =====================================
output.logstash:
  hosts: []
  ssl.certificate_authorities: ['/etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt']
